version: 2

models:
    - name: ml_past_games_analysis
      description: Historical Table showing past ML Game Predictions
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 1
        - dbt_expectations.expect_column_pair_values_A_to_be_greater_than_B:
            column_A: tot_games
            column_B: tot_correct_predictions
            or_equal: False
    - name: ml_past_games
      description: Historical Table showing past Games w/ outcomes before ML Predictions
      tests:
        - dbt_expectations.expect_compound_columns_to_be_unique:
            column_list: ["home_team", "away_team", "proper_date"]
      columns:
        - name: outcome
          tests:
            - not_null
    - name: ml_tonights_games
      description: Table showing Tonight's Games that will get fed into ML Models
      tests:
        - dbt_expectations.expect_compound_columns_to_be_unique:
            column_list: ["home_team", "away_team", "proper_date"]
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 1
            max_value: 15
      columns:
        - name: away_is_top_players
          tests:
            - not_null
        - name: home_is_top_players
          tests:
            - not_null
        - name: home_days_rest
          tests:
            - not_null
        - name: away_days_rest
          tests:
            - not_null