repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.2.1
    hooks:
      - id: sqlfluff-fix
        additional_dependencies:
          - sqlfluff-templater-dbt==4.2.1
        args:
          - --config=pyproject.toml
          - --templater=jinja
          - --ignore=templating
          - --disable-progress-bar
        files: ^(models|macros|snapshots|tests)/.*\.sql$
      - id: sqlfluff-lint
        additional_dependencies:
          - sqlfluff-templater-dbt==4.2.1
        args:
          - --config=pyproject.toml
          - --templater=jinja
          - --ignore=templating
          - --disable-progress-bar
        files: ^(models|macros|snapshots|tests)/.*\.sql$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        types: [yaml]
