
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nba_elt_project'
version: '1.0.0'
config-version: 2

vars:
  'dbt_date:time_zone': 'America/Chicago'

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  nba_elt_project:
      # Applies to all files under models/example/
      marts:
        +materialized: table
        +schema: nba_prod
        +tags:
          - "NBA_PRODUCTION_MARTS"
          - "DAILY"
      reporting:
        +materialized: view
        +schema: reporting
        +tags:
          - "REPORTING"
      prep:
        +materialized: table
        +schema: nba_prep
        +tags:
          - "NBA_PRODUCTION_PREP"
          - "DAILY"
      staging:
        +materialized: table
        +schema: nba_staging
        +tags:
          - "NBA_PRODUCTION_STAGING"
          - "DAILY"
      operations:
        +materialized: view
        +schema: operations
        +tags:
          - "NBA_PRODUCTION_OPERATIONS"
          - "DAILY"
      ml:
        +materialized: table
        +schema: ml_models
        +tags:
          - "NBA_PRODUCTION_ML_MODELS"
          - "DAILY"
      ad_hoc_analytics:
        +materialized: view
        +schema: ad_hoc_analytics
        +tags:
          - "ANALYTICS"
          - "AD HOC"
          - "VIEW"
      fact:
        +materialized: table
        +schema: fact
        +tags:
          - "DAILY"
      dim:
        +materialized: table
        +schema: dim
        +tags:
          - "DAILY"
seeds:
  nba_elt_project:
    +schema: nba_source
    +tags:
      - "NBA_PRODUCTION_STAGING"
