[tool.poetry]
name = "nba-elt-dbt"
version = "2.5.4"
description = "dbt Transformations for NBA ELT Project"
authors = ["jyablonski9 <jyablonski9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dbt-core = "1.6.5"
dbt-postgres = "1.6.5"
pytz = "2023.3.post1"

[tool.poetry.group.dev.dependencies]
sqlfluff = "2.3.5"
sqlfluff-templater-dbt = "2.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"