[tool.poetry]
name = "nba-elt-dbt"
version = "2.3.1"
description = "dbt Transformations for NBA ELT Project"
authors = ["jyablonski9 <jyablonski9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dbt-core = "^1.6.5"
dbt-postgres = "^1.6.5"
pytz = "^2023.3.post1"

[tool.poetry.group.dev.dependencies]
sqlfluff = "^2.3.2"
sqlfluff-templater-dbt = "^2.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.sqlfluff.core]
dialect = "postgres"
templater = "dbt"
exclude_rules = "L016,L027,L029,L032,L034"
large_file_skip_byte_limit = "25000"

# L016 - line too long gahbage
# L027 - i do select a, b instead of foo.a, vee.b - bad habit but excluding for now
# L029 - no sql-reserved keywords as aliases - bad habit but excluding for now
# L032 - no `using` keyword for joins - this is fine imo so fuqqit
# L034 - really fucked up my shit tbh

[tool.sqlfluff.templater.dbt]
project_dir = "./"
exclude = [
    "target/",
    "dbt_modules/",
    "macros/",
    "logs"
]


[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.identifiers]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.literals]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.types]
extended_capitalisation_policy = "lower"

[tool.sqlfluff.indentation]
indented_joins = "True"
