version: 2

models:
  - name: prep_boxscores_table
    description: Prep table for boxscores data
    columns:
      - name: team
        tests:
          - not_null
  - name: prep_schedule_table
    description: Prep table for schedule + odds data
    columns:
      - name: away_team
        tests:
          - not_null
      - name: home_team
        tests:
          - not_null
  - name: prep_standings_table
    description: Prep table for standings table
    columns:
      - name: wins_last_10
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10
      - name: losses_last_10
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10
      - name: projected_wins
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 82
      - name: projected_losses
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 82