version: 2

models:
  - name: prep_boxscores_table
    description: Prep table for boxscores data
    columns:
      - name: team
        tests:
          - not_null
  - name: prep_schedule_table
    description: Prep table for schedule + odds data
    columns:
      - name: away_team
        tests:
          - not_null
      - name: home_team
        tests:
          - not_null