default:
  target: sqlfluff
  outputs:
    sqlfluff:
      type: postgres
      host: "{{ env_var('dbt_host') }}"
      port: "{{ env_var('dbt_port') }} "
      dbname: "{{ env_var('dbt_dbname') }}"
      schema: "{{ env_var('dbt_schema') }}"
      user: "{{ env_var('dbt_user') }}"
      password: "{{ env_var('dbt_pass') }}"
