services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jacob_db
    volumes:
      - ${PWD}/docker/postgres_bootstrap.sql:/docker-entrypoint-initdb.d/postgres_bootstrap.sql
    networks:
      - api_network

  dbt_runner:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: nba_elt_dbt_local
    environment:
      - DBT_PRAC_KEY=docker_dev
    depends_on:
      - postgres
    networks:
      - api_network
    links:
      - postgres:postgres
    # have to run +state:modified+ to re-create the parent dependencies on any changed models during ci

    # command: dbt build --profiles-dir profiles/ --profile dbt_ci --select +state:modified+ --state ./target/
    command: dbt build --profiles-dir profiles/ --profile dbt_ci

networks:
  api_network:
