version: 2

models:
    - name: staging_aws_adv_stats_table
      description: Staging table for advanced stats
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
        - name: team
          tests:
            - unique
            - not_null
            - dbt_expectations.expect_column_to_exist
    - name: staging_aws_boxscores_table
      description: Staging table for box scores
      columns:
        - name: player
          tests:
            - not_null
        - name: location
          tests:
            - not_null
        - name: pts
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 0  
                max_value: 100
        - name: plusminus
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: -70 
                max_value: 70
        - name: games_played
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 1
                max_value: 82
    - name: staging_aws_contracts_table
      description: Staging table for box scores
      columns:
        - name: player
          tests:
            - not_null
        - name: salary
          tests:
            - not_null
    - name: staging_aws_injury_data_table
      description: Staging table for box scores
      columns:
        - name: player
          tests:
            - not_null
        - name: team
          tests:
            - not_null
        - name: injury
          tests:
            - not_null
        - name: description
          tests:
            - not_null
    - name: staging_aws_odds_table
      description: Staging table for box scores
      columns:
        - name: team
          tests:
            - not_null
        - name: date
          tests:
            - not_null
        - name: time
          tests:
            - not_null
        - name: spread
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: -20  
                max_value: 20 
        - name: total
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 150  
                max_value: 300 
        - name: moneyline
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: -1500  
                max_value: 800
    - name: staging_aws_reddit_data_table
      description: Staging table for box scores
      columns:
        - name: scrape_date
          tests:
            - not_null
        - name: scrape_time
          tests:
            - not_null
    - name: staging_aws_schedule_table
      description: Staging table for box scores
      columns:
        - name: away_team
          tests:
            - not_null
        - name: home_team
          tests:
            - not_null
        - name: proper_date
          tests:
            - not_null
    - name: stg_aws_stats_table
      description: Staging table for box scores
      columns:
        - name: player
          tests:
            - not_null
    - name: stg_aws_transactions_table
      description: Staging table for box scores
      columns:
        - name: date
          tests:
            - not_null
        - name: transaction
          tests:
            - not_null