/*         COALESCE("3p%"::text::numeric) as three_p_percent, */
SELECT  player::text,
        pos::text,
        age::integer,
        tm::text,
        g::integer,
        gs::integer,
        mp::text,
        fg::numeric,
        fga::numeric,
        "fg%"as fg_percent,
        "3p" as three_p,
        "3pa" as three_p_attempted,
        "3p%" as three_p_percent,
        "2p" as two_p,
        "2pa" as two_p_attempted,
        "2p%" as two_p_percent,
        "efg%" as efg_percent,
        "ft%" as ft_percent,
        orb::numeric,
        drb::numeric,
        trb::numeric,
        ast::numeric,
        stl::numeric,
        blk::numeric,
        tov::numeric,
        pf::numeric,
        pts::numeric

FROM {{ source('nba_source', 'aws_stats_source')}}
WHERe player IS NOT NULL