version: 2

models:
    - name: prod_twitter_comments
      description: Prod Twitter Comment Data
      tests:
        - dbt_expectations.expect_compound_columns_to_be_unique:
            column_list: ["username", "tweet", "created_at"]
      columns:
          - name: created_at
            description: Only grab the latest available date of data
          - name: url
            tests:
                - not_null
          - name: compound
            tests:
                - not_null
          - name: neg
            tests:
                - not_null
          - name: neu
            tests:
                - not_null
          - name: pos
            tests:
                - not_null