version: 2

models:
    - name: prod_schedule
      description: Prod Season Schedule Table
      columns:
      - name: avg_team_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 30