version: 2

models:
    - name: prod_past_schedule_analysis
      description: Prod Past Games Schedule Analysis Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
          - name: team
            tests:
                - unique
                - not_null