version: 2

models:
    - name: prod_gamelogs
      description: Prod Game Logs Table
      tests:
        - dbt_expectations.expect_compound_columns_to_be_unique:
            column_list: ["player", "date"]