version: 2

models:
    - name: prod_team_blown_leads
      description: Prod Team Blown Leads + Team Comebacks Table - 30 rows for reg season + 16 for playoffs
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 46
      columns:
          - name: team
            description: Team Acronym
            tests:
                - unique
                - not_null