version: 2

models:
    - name: prod_opp_stats
      description: Prod Opponent Shooting Stats Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
          - name: fg_percent_opp
            tests:
                - not_null
          - name: threep_percent_opp
            tests:
                - not_null
          - name: threep_made_opp
            tests:
                - not_null
          - name: ppg_opp
            tests:
                - not_null