
version: 2

models:
    - name: prod_odds_winners_losers
      description: Prod Odds Winners Losers
      tests:
        - dbt_expectations.expect_compound_columns_to_be_unique:
            column_list: ["team", "date"]