version: 2

models:
    - name: prod_injuries
      description: Prod Injuries Table
      columns:
          - name: player
            tests:
                - not_null
          - name: team_acronym
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "[A-Z]{3}"
      tests:
        - dbt_expectations.expect_compound_columns_to_be_unique:
            column_list: ["player", "injury", "description"]
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 0
            max_value: 200