version: 2

models:
  - name: prod_team_record_daily_rollup
    columns:
      - name: team
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: running_total_games_played
        tests:
          - not_null