version: 2

models:
    - name: prod_team_adv_stats
      description: Prod Team Advanced Stats Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
          - name: Team
            description: Team Acronym
            tests:
                - unique
                - not_null