version: 2

models:
    - name: prod_future_schedule_analysis
      description: Teams Future Schedule Analysis
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
          - name: team
            tests:
                - unique
                - not_null
          - name: pct_games_left_home
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
          - name: pct_games_left_road
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
          - name: pct_games_left_above_500
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
          - name: pct_games_left_below_500
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1