version: 2

models:
    - name: prod_team_adv_stats
      description: Prod Team Advanced Stats Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
          - name: Team
            description: Team Acronym
            tests:
                - unique
                - not_null
    - name: prod_schedule
      description: Prod Season Schedule Table
      columns:
      - name: avg_team_rank
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 30
    - name: prod_pbp
      description: Prod Play by Play Table
    - name: prod_recent_games_players
      description: Prod Recent Games for Players Table
      tests:
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 12
            max_value: 20
      columns:
      - name: pts_color
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 3
      - name: ts_color
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 3
    - name: prod_recent_games_teams
      description: Prod Recent Games for Teams Table
      tests:
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 2
            max_value: 30
    - name: prod_standings
      description: Prod Standings Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      # - dbt_expectations.expect_multicolumn_sum_to_equal:
          # column_list: ["wins_last_10", "losses_last_10"]
          # sum_total: 10
    - name: prod_team_injuries
      description: Prod Team Injuries Table
      tests:
        - dbt_expectations.expect_table_row_count_to_be_between:
            min_value: 0
            max_value: 200
    - name: prod_team_ratings
      description: Prod Team Ratings Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
    - name: prod_team_blown_leads
      description: Prod Team Blown Leads + Team Comebacks Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
    - name: prod_mov
      description: Prod Team Margin of Victory Table
    - name: prod_transactions
      description: Prod League Transactions Table
      columns:
      - name: transaction
        tests:
          - not_null
    - name: prod_bans
      description: Prod Big ASS numbers table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 2
    - name: prod_game_types
      description: Prod Game Types Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 3
    - name: prod_opp_stats
      description: Prod Opponent Shooting Stats Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
    - name: prod_preseason_odds
      description: Prod Preseason Odds Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
    - name: prod_scorers
      description: Prod Scoring Stats Table
    - name: prod_team_contracts_analysis
      description: Prod Team Contracts Table
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
    - name: prod_gamelogs
      description: Prod Game Logs Table
    - name: prod_contract_value_analysis
      description: Player Contract Value Analysis Table (WIP)
      columns:
          - name: player
            tests:
                - unique
                - not_null
          - name: adj_penalty_final
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0.75
                  max_value: 1
          - name: pct_penalized
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 0.25
          - name: rankingish
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
    - name: prod_future_schedule_analysis
      description: Teams Future Schedule Analysis
      tests:
        - dbt_expectations.expect_table_row_count_to_equal:
            value: 30
      columns:
          - name: team
            tests:
                - unique
                - not_null
          - name: pct_games_left_home
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
          - name: pct_games_left_road
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
          - name: pct_games_left_above_500
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1
          - name: pct_games_left_below_500
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 1