version: 2

models:
    - name: prod_adv_stats
      description: Prod Team Advanced Stats Table
      columns:
          - name: Team
            description: Team Acronym
            tests:
                - unique
                - not_null
    - name: prod_schedule
      description: Prod Season Schedule Table
