{% macro convert_team_names_flairs(column_name) %}

CASE WHEN {{ column_name }} IN ('Hawks')  THEN 'ATL'
     WHEN {{ column_name }} IN ('Celtics', 'bwBos')  THEN 'BOS'
     WHEN {{ column_name }} IN ('Nets')  THEN 'BKN'
     WHEN {{ column_name }} IN ('ChaHornets')  THEN 'CHA'
     WHEN {{ column_name }} IN ('Bulls')  THEN 'CHI'
     WHEN {{ column_name }} IN ('Cavaliers')  THEN 'CLE'
     WHEN {{ column_name }} IN ('Mavs', 'bwDal')  THEN 'DAL'
     WHEN {{ column_name }} IN ('Nuggets')  THEN 'DEN'
     WHEN {{ column_name }} IN ('Pistons')  THEN 'DET'
     WHEN {{ column_name }} IN ('Warriors', 'bwGsw', 'bwWarriors')  THEN 'GSW'
     WHEN {{ column_name }} IN ('Rockets', 'SanDiegoRockets')  THEN 'HOU'
     WHEN {{ column_name }} IN ('Pacers')  THEN 'IND'
     WHEN {{ column_name }} IN ('Clippers', 'bwLac')  THEN 'LAC'
     WHEN {{ column_name }} IN ('Lakers')  THEN 'LAL'
     WHEN {{ column_name }} IN ('Grizzlies', 'VanGrizzlies', 'bwMem')  THEN 'MEM'
     WHEN {{ column_name }} IN ('Heat', 'bwMia')  THEN 'MIA'
     WHEN {{ column_name }} IN ('Bucks', 'bwMil')  THEN 'MIL'
     WHEN {{ column_name }} IN ('Timberwolves', 'bwMin')  THEN 'MIN'
     WHEN {{ column_name }} IN ('Pelicans')  THEN 'NOP'
     WHEN {{ column_name }} IN ('Knicks', 'tKnicks')  THEN 'NYK'
     WHEN {{ column_name }} IN ('Thunder')  THEN 'OKC'
     WHEN {{ column_name }} IN ('Magic')  THEN 'ORL'
     WHEN {{ column_name }} IN ('TrailBlazers')  THEN 'POR'
     WHEN {{ column_name }} IN ('76ers', 'bwPhi')  THEN 'PHI'
     WHEN {{ column_name }} IN ('Suns', 'bwPhx')  THEN 'PHX'
     WHEN {{ column_name }} IN ('Kings')  THEN 'SAC'
     WHEN {{ column_name }} IN ('Spurs')  THEN 'SAS'
     WHEN {{ column_name }} IN ('Raptors', 'TampaRaptors')  THEN 'TOR'
     WHEN {{ column_name }} IN ('Jazz')  THEN 'UTA'
     WHEN {{ column_name }} IN ('Wizards', 'Bullets')  THEN 'WAS'
     WHEN {{ column_name }} IN ('NBA', 'SuperSonics')  THEN 'NBA'
     ELSE 'RANDOM FLAIR'
END
{% endmacro %}
