# https://github.com/sqlfluff/sqlfluff-github-actions/tree/main/menu_of_workflows
name: Lint Models

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.ci_cd
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff==0.10.1 markupsafe==2.0.1 sqlfluff-templater-dbt==0.10.1"

      - name: Lint models
        run: "sqlfluff lint models"