version: 2

sources:
  - name: nba_source
    database: jacob_db
    description: Landing Zone for NBA Source Data
    tables:
      - name: aws_stats_source
        description: Raw player aggregate stats
        tags: [NBA PRODUCTION - SOURCE]
      - name: aws_boxscores_source
        description: Raw player boxscores
        tags: [NBA PRODUCTION - SOURCE]
      - name: aws_injury_data_source
        description: Raw player injury data
        tags: [NBA PRODUCTION - SOURCE]
        columns:
          - name: player
            tests:
              - not_null
          - name: team
            tests:
              - not_null
          - name: description
            tests:
              - not_null
      - name: aws_transactions_source
        description: Raw player & team trades + transactions
        tags: [NBA PRODUCTION - SOURCE]
        columns:
          - name: date
            tests:
              - not_null
          - name: transaction
            tests:
              - not_null
      - name: aws_adv_stats_source
        description: Raw team advanced stats
        tags: [NBA PRODUCTION - SOURCE]
        columns:
          - name: team
            tests:
              - unique
              - not_null
      - name: aws_reddit_data_source
        description: Raw reddit data 
        tags: [NBA PRODUCTION - SOURCE]
        loaded_at_field: scrape_time
        freshness:
          warn_after: {count: 480, period: hour}
          error_after: {count: 720, period: hour}
      - name: aws_schedule_source
        description: Raw Schedule table
        tags: [NBA PRODUCTION - SOURCE]
        columns:
          - name: away_team
            tests:
              - not_null
          - name: home_team
            tests:
              - not_null
          - name: proper_date
            tests:
              - not_null
      - name: aws_odds_source
        description: Raw Odds table
        tags: [NBA PRODUCTION - SOURCE]
        columns:
          - name: team
            tests:
              - not_null
          - name: date
            tests:
              - not_null
          - name: datetime1
            tests:
              - not_null
        loaded_at_field: datetime1
        freshness:
          warn_after: {count: 700, period: hour}
          error_after: {count: 1400, period: hour}
      - name: aws_contracts_source
        description: Raw contracts table
        tags: [NBA PRODUCTION - SOURCE]