version: 2

sources:
  - name: nba_source
    database: jacob_db
    description: Landing Zone for NBA Source Data
    tables:
      - name: bbref_player_stats_snapshot
        description: Raw player aggregate stats
      - name: twitter_tweets
        description: Raw twitter data
      - name: twitter_tweepy_legacy
        description: Raw twitter tweepy data (2022-07-13)
        loaded_at_field: scrape_ts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
      - name: bbref_player_boxscores
        description: Raw player boxscores
        columns:
          - name: player
            data_tests:
              - not_null
          - name: team
            data_tests:
              - not_null
      - name: bbref_player_injuries
        description: Raw player injury data
        columns:
          - name: player
            data_tests:
              - not_null
          - name: team
            data_tests:
              - not_null
          - name: description
            data_tests:
              - not_null
      - name: bbref_league_transactions
        description: Raw player & team trades + transactions
        columns:
          - name: date
            data_tests:
              - not_null
          - name: transaction
            data_tests:
              - not_null
      - name: bbref_team_adv_stats_snapshot
        description: Raw team advanced stats
        columns:
          - name: team
            data_tests:
              - not_null
      - name: internal_team_top_players
        columns:
          - name: player
            data_tests:
              - not_null
      - name: internal_player_attributes
        columns:
          - name: player
            data_tests:
              - not_null
      - name: internal_team_attributes
        columns:
          - name: team
            data_tests:
              - not_null
      - name: reddit_posts
        description: Raw reddit data 
        loaded_at_field: scrape_time
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
      - name: reddit_comments
        description: Raw reddit comment data
        loaded_at_field: scrape_ts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
        columns:
          - name: url
            data_tests:
              - not_null
      - name: bbref_league_schedule
        description: Raw Schedule table
        columns:
          - name: away_team
            data_tests:
              - not_null
          - name: home_team
            data_tests:
              - not_null
          - name: proper_date
            data_tests:
              - not_null
      - name: draftkings_game_odds
        description: Raw Odds table
        columns:
          - name: team
            data_tests:
              - not_null
          - name: date
            data_tests:
              - not_null
          - name: datetime1
            data_tests:
              - not_null
        loaded_at_field: datetime1
        freshness:
          warn_after: {count: 124, period: day}
          error_after: {count: 256, period: day}
      - name: bbref_player_contracts
        description: Raw contracts table
        columns:
          - name: player
            data_tests:
              - not_null
      - name: bbref_player_pbp
        description: Raw pbp table
        columns:
          - name: hometeam
            data_tests:
              - not_null
          - name: awayteam
            data_tests:
              - not_null
          - name: timequarter
            data_tests:
              - not_null
      - name: bbref_team_preseason_odds
        description: Raw preseason odds table
        data_tests:
          - dbt_expectations.expect_table_row_count_to_equal:
              value: 30
        columns:
          - name: team
            data_tests:
              - unique
              - not_null
      - name: bbref_team_opponent_shooting_stats
        description: Raw Team Opponent Stats Table
        columns:
          - name: team
            data_tests:
              - not_null
      - name: bbref_player_shooting_stats
        description: Raw Player Shooting Stats table
        columns:
          - name: player
            data_tests:
              - not_null
      - name: internal_league_inactive_dates
        description: Inactive Dates table to manually override Schedule Tests
      - name: play_in_details
  - name: ml
    database: jacob_db
    schema: ml
    description: Landing Zone for NBA ML Data
    tables:
      - name: ml_game_predictions
        columns:
          - name: game_date
            data_tests:
              - not_null
  - name: marts
    database: jacob_db
    schema: marts
    tables:
      - name: user_predictions