version: 2

sources:
  - name: nba_source
    database: jacob_db
    description: Landing Zone for NBA Source Data
    tables:
      - name: aws_stats_source
        description: Raw player aggregate stats
      - name: aws_twitter_data_source
        description: Raw twitter data
      - name: aws_twitter_tweepy_data_source
        description: Raw twitter tweepy data (2022-07-13)
        loaded_at_field: scrape_ts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
      - name: aws_boxscores_source
        description: Raw player boxscores
        columns:
          - name: player
            tests:
              - not_null
          - name: team
            tests:
              - not_null
      - name: aws_injury_data_source
        description: Raw player injury data
        columns:
          - name: player
            tests:
              - not_null
          - name: team
            tests:
              - not_null
          - name: description
            tests:
              - not_null
      - name: aws_transactions_source
        description: Raw player & team trades + transactions
        columns:
          - name: date
            tests:
              - not_null
          - name: transaction
            tests:
              - not_null
      - name: aws_adv_stats_source
        description: Raw team advanced stats
        columns:
          - name: team
            tests:
              - not_null
      - name: team_top_players
        columns:
          - name: player
            tests:
              - not_null
      - name: aws_player_attributes_source
        columns:
          - name: player
            tests:
              - not_null
      - name: aws_team_attributes_source
        columns:
          - name: team
            tests:
              - not_null
      - name: aws_reddit_data_source
        description: Raw reddit data 
        loaded_at_field: scrape_time
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
      - name: aws_reddit_comment_data_source
        description: Raw reddit comment data
        loaded_at_field: scrape_ts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 72, period: hour}
        columns:
          - name: url
            tests:
              - not_null
      - name: aws_schedule_source
        description: Raw Schedule table
        columns:
          - name: away_team
            tests:
              - not_null
          - name: home_team
            tests:
              - not_null
          - name: proper_date
            tests:
              - not_null
      - name: aws_odds_source
        description: Raw Odds table
        columns:
          - name: team
            tests:
              - not_null
          - name: date
            tests:
              - not_null
          - name: datetime1
            tests:
              - not_null
        loaded_at_field: datetime1
        freshness:
          warn_after: {count: 124, period: day}
          error_after: {count: 256, period: day}
      - name: aws_contracts_source
        description: Raw contracts table
        columns:
          - name: player
            tests:
              - not_null
      - name: aws_pbp_data_source
        description: Raw pbp table
        columns:
          - name: hometeam
            tests:
              - not_null
          - name: awayteam
            tests:
              - not_null
          - name: timequarter
            tests:
              - not_null
      - name: aws_preseason_odds_source
        description: Raw preseason odds table
        tests:
          - dbt_expectations.expect_table_row_count_to_equal:
              value: 30
        columns:
          - name: team
            tests:
              - unique
              - not_null
      - name: aws_opp_stats_source
        description: Raw Team Opponent Stats Table
        columns:
          - name: team
            tests:
              - not_null
      - name: aws_shooting_stats_source
        description: Raw Player Shooting Stats table
        columns:
          - name: player
            tests:
              - not_null
      - name: player_attributes
        description: Player Attributes v2 Table
        columns:
          - name: player
            tests:
              - not_null
  - name: ml_models
    database: jacob_db
    schema: ml_models
    description: Landing Zone for NBA ML Data
    tables:
      - name: ml_game_predictions
        columns:
          - name: game_date
            tests:
              - not_null
  - name: nba_prod
    database: jacob_db
    schema: nba_prod
    tables:
      - name: user_predictions